<?php
define("NOMBRE_PHOTO_ALBUM",18);
define("NOMBRE_PHOTO_JOURNAL",5);
define("NOMBRE_PHOTO_PROJET",18);
define("NOMBRE_ARTICLE_PAGE_JOURNAL",10);
define("CHEMIN_BASE",$_SERVER['DOCUMENT_ROOT']);
?>